<?php
/**
 * Checkout. Payment method template
 * 
 * @see Payparts_Payment_Block_Checkout_Method
 */
/*@var $this Payparts_Payment_Block_Checkout_Method*/
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="form-list" data-is-selected="<?php echo $this->isSelect(); ?>">
    <li id="payparts-select-block">
        <p class="payment-method">
            <label for="month-sel">Срок,мес.</label>
            <select id="month-sel" name="partsCount">
                <option disabled>Срок,мес.</option>
                <?php foreach ($this->getAvailablePeriods() as $period): ?>
                <option value="<?php echo $period; ?>"><?php echo $period; ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <?php if ($this->getDescription()): ?>
        <p class="payment-description">
            <?php echo $this->getDescription(); ?>
        </p>
        <?php endif; ?>
    </li>
</ul>
<style type="text/css">
    .payment-method, .payment-description {
        text-align: left;
    }
    .payment-description {
        margin-top: 5px;
    }
</style>
